objects/Order.object
<CustomObject>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>gross__c</fullName>
        <label>gross</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>net__c</fullName>
        <label>net</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>quantity__c</fullName>
        <label>quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
</CustomObject>

objects/Visit__c.object
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/order/CartController.cls
/**
 * Created by Adam.Czyzynski on 14-Aug-17.
 */

public with sharing class CartController {

    private Account orderOwner;

    private List<OrderItem> orderProduct2s;

    private List<Product2> availableProduct2s;

    private Order order;

    private Visit__c visit;

    public void createNewOrder(Order order, Account account, Visit__c visit){
        this.orderOwner = account;
        this.visit = visit;
        this.order = order;
    }

    public void addNewProductToOrder(OrderItem orderItem){
        orderProduct2s.add(orderItem);
    }

    public List<Product2> getProduct2s(){

        return this.sampleData();
    }


    private List<Product2> sampleData(){
        List<Product2> product2s = Database.query('SELECT Name, Id, gross__c, net__c, quantity__c FROM Product2');
        return  product2s;
    }

public List<Product2> getAvailableProductList(){
return null;
        }

}