objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Value__c</fullName>
        <label>Order Value gross</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order Value Net</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Visit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Visit</label>
        <referenceTo>Visit__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Order</fullName>
        <active>true</active>
        <label>Order</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Visit__c.object
<CustomObject>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderList.cls
/**
 * Created by Adam.Czyzynski on 16-Aug-17.
 */

public with sharing class OrderList {

    private String id = ApexPages.currentPage().getParameters().get('id');


    public User getUser(){
        User user = new User(AboutMe='asd', LastName='aas');
        return user;
    }
    public List<Order> getOrders() {
        Apexpages.currentPage().getHeaders().put('X-UA-Compatible', 'IE=edge');
        List<Order> orders = Database.query('SELECT Description, EndDate, Visit__c, Order_Value__c, Order__c, RecordType.Name, Id FROM Order WHERE AccountId=:id');
        return orders;

    }




}