objects/Visit__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Visits</relationshipLabel>
        <relationshipName>Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Finished__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Visit</label>
    <nameField>
        <label>Visit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VisitsListController.cls
/**
 * Created by Adam.Czyzynski on 8/9/2017.
 */

public with sharing class VisitsListController {

    private List<Visit__C> visits = new List<Visit__C>();

    public List<Visit__c> getVisits(){
        List<Visit__c> results = [SELECT Finished__c, Date__c, CreatedById, Name
                FROM Visit__c
            //    WHERE Account__c=:UserInfo.getUserId()
        ];
        return results;
    }



}